### ISSUE TITLE
App crash when launched in Landscape Mode

### ISSUE THREAD

**Issue by X-Tender** [jasonkneen/com.jasonkneen.dynamicTSS#1]
Got the following issue.
When I start my App and have the Device in Portrait Mode it works as have.

When I start it, while the Device is in Landscape mode, the App Crash after I open the window / controller with the Widget. Thats the Callstack.

```
[ERROR] AndroidRuntime: FATAL EXCEPTION: main
[ERROR] AndroidRuntime: Process: de.xxx.xx.xxx, PID: 23612
[ERROR] AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.xxx.xx.xxx/org.appcelerator.titanium.TiActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
[ERROR] AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2378)
[ERROR] AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2440)
[ERROR] AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:162)
[ERROR] AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
[ERROR] AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
[ERROR] AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5430)
[ERROR] AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
[ERROR] AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
[ERROR] AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
[ERROR] AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
[ERROR] AndroidRuntime:     at ti.modules.titanium.ui.widget.TiView.<init>(TiView.java:25)
[ERROR] AndroidRuntime:     at ti.modules.titanium.ui.ViewProxy.createView(ViewProxy.java:33)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:483)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:507)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:507)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:507)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:670)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:564)
[ERROR] AndroidRuntime:     at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:232)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:32)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:451)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:533)
[ERROR] AndroidRuntime:     at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6097)
[ERROR] AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
[ERROR] AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
[ERROR] AndroidRuntime:     ... 10 more
```

SDK: 3.5.1.GA
Runs on Android 5.1

**Comment by X-Tender** [comment]
OK, with a little bit of trial and Error I found the issue.
I have a View with no layout assigned to it and in my TSS I have this style:

```
"#carBlueprintView" : {
    backgroundColor     : Alloy.CFG.colors.brightBlue,
    height              : Ti.UI.SIZE,
    top                 : 0,

    landscape: {
        width           : "40%",
        height          : Ti.UI.FILL,
        left            : 0
    },

    portrait: {
        height          : Ti.UI.SIZE,
        width           : Ti.UI.FILL
    }
}
```

when I add to the `portrait` this style `layout             : "vertical",` it crashes. Actually I didnt wanted to add the layout to it so I just removed it and it worked.

Don't know If its my fault or an Issue in the widget.
